// Ethereum Wallets
export const ethereumWallets = [
  {
    name: "MetaMask",
    flag: "isMetaMask",
    isAvailable: false,
    provider: undefined,
    icon: "",
    rdns: "",
  },
  {
    name: "Coinbase Wallet",
    flag: "isCoinbaseWallet",
    isAvailable: false,
    provider: undefined,
    icon: "",
    rdns: "",
  },
  {
    name: "Trust Wallet",
    flag: "isTrustWallet",
    isAvailable: false,
    provider: undefined,
    icon: "",
    rdns: "",
  },
  {
    name: "Binance Wallet",
    flag: "isBinanceWallet",
    isAvailable: false,
    provider: undefined,
    icon: "",
    rdns: "",
  },
  {
    name: "Token Pocket",
    flag: "isTokenPocket",
    isAvailable: false,
    provider: undefined,
    icon: "",
    rdns: "",
  },
  {
    name: "Safe Pal",
    flag: "isSafePal",
    isAvailable: false,
    provider: undefined,
    icon: "",
    rdns: "",
  },
  {
    name: "Math Wallet",
    flag: "isMathWallet",
    isAvailable: false,
    provider: undefined,
    icon: "",
    rdns: "",
  },
  {
    name: "Nifty Wallet",
    flag: "isNiftyWallet",
    isAvailable: false,
    provider: undefined,
    icon: "",
    rdns: "",
  },
  {
    name: "Dapper Wallet",
    flag: "isDapperWallet",
    isAvailable: false,
    provider: undefined,
    icon: "",
    rdns: "",
  },
  {
    name: "Brave Wallet",
    flag: "isBraveWallet",
    isAvailable: false,
    provider: undefined,
    icon: "",
    rdns: "",
  },
];

// Solana Wallets
export const solanaWallets = [
  { name: "Phantom", flag: "isPhantom", isAvailable: false },
  { name: "Solflare", flag: "isSolflare", isAvailable: false },
  { name: "Backpack", flag: "isBackpack", isAvailable: false },
  { name: "Glow", flag: "isGlow", isAvailable: false },
  { name: "Slope", flag: "isSlope", isAvailable: false },
  { name: "Coin98", flag: "isCoin98", isAvailable: false },
  { name: "BitKeep", flag: "isBitKeep", isAvailable: false },
  { name: "MathWallet", flag: "isMathWallet", isAvailable: false },
  { name: "TokenPocket", flag: "isTokenPocket", isAvailable: false },
  { name: "BraveWallet", flag: "isBraveWallet", isAvailable: false },
  { name: "Torus", flag: "isTorus", isAvailable: false },
  { name: "Exodus", flag: "isExodus", isAvailable: false },
  { name: "Ledger", flag: "isLedger", isAvailable: false },
  { name: "Sollet", flag: "isSollet", isAvailable: false },
  { name: "Solong", flag: "isSolong", isAvailable: false },
  { name: "SafePal", flag: "isSafePal", isAvailable: false },
  { name: "Trust", flag: "isTrust", isAvailable: false },
  { name: "Zelcore", flag: "isZelcore", isAvailable: false },
  { name: "Coinbase Wallet", flag: "isCoinbaseWallet", isAvailable: false },
];

// Cardano Wallets
export const cardanoWallets = [
  { name: "Yoroi", flag: "isYoroi", isAvailable: false },
  { name: "Daedalus", flag: "isDaedalus", isAvailable: false },
  { name: "NamiWallet", flag: "isNamiWallet", isAvailable: false },
  { name: "Typhon", flag: "isTyphon", isAvailable: false },
  { name: "Lace", flag: "isLace", isAvailable: false },
  { name: "GeroWallet", flag: "isGeroWallet", isAvailable: false },
  { name: "Flint", flag: "isFlint", isAvailable: false },
  { name: "Eternl", flag: "isEternl", isAvailable: false },
  { name: "Seiza", flag: "isSeiza", isAvailable: false },
  { name: "Lace", flag: "lace", isAvailable: false },
];
